cc_binary(
    name = "send-message",
    srcs = ["send-message.c"],
    deps = [
        "//mam:mam_client",
    ],
)

cc_binary(
    name = "receive",
    srcs = ["receive.c"],
    deps = [
        "//mam:mam_client",
    ],
)